name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            deps: sudo apt-get update && sudo apt-get install -y cmake build-essential libexiv2-dev libtag1-dev zlib1g-dev pkg-config
          - os: macos-latest
            deps: brew install cmake exiv2 taglib zlib pkg-config
          - os: windows-latest
            deps: echo "no extra deps on Windows"

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: ${{ matrix.deps }}
      shell: bash

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ctest --test-dir build --output-on-failure
